# =========================================================
# SERVER
# =========================================================

server.port=${PORT:4000}

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false

server.tomcat.max-swallow-size=2MB
server.tomcat.max-http-form-post-size=2MB

server.compression.enabled=true


# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/mindcart
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.hikari.maximum-pool-size=${DB_POOL_SIZE:10}
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.max-lifetime=1700000
spring.datasource.hikari.leak-detection-threshold=30000


# =========================================================
# JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=validate


# =========================================================
# DATABASE INITIALIZATION
# =========================================================

#spring.sql.init.mode=${SQL_INIT_MODE:always}


# =========================================================
# LOGGING
# =========================================================




# =========================================================
# JWT
# =========================================================

app.jwt.secret= RujOkItwns9drG/hFqC32WkH4wrDb7rqmwEi0Y33dfGawTkGpjCvg92fWAZJM5uk93NX2E4POSC63ZN/L6EASg==


# =========================================================
# CORS
# =========================================================

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8081}


PUSH_ENABLED=true
EXPO_ACCESS_TOKEN=